PREFIX era-sh: <http://data.europa.eu/949/shapes/>

DELETE {
    ?s ?p ?o .
}
WHERE {
    ?s ?p ?o .
    FILTER (?s IN (
        era-sh:NoDeprecatedRangeInDatatypePropertyShape,
        era-sh:NoDeprecatedRangeInObjectPropertyShape,
        era-sh:NoDeprecatedDomainInDatatypePropertyShape,
        era-sh:NoDeprecatedDomainInObjectPropertyShape
    ))
}